-- Rode este arquivo UMA VEZ no SQL Editor do seu projeto Supabase.
-- Depois, em Authentication > Providers, mantenha Email habilitado e desative novos cadastros públicos.
-- Crie manualmente o seu usuário administrador em Authentication > Users.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id text not null,
  event_name text not null,
  page text,
  meta jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);
create index if not exists analytics_events_visitor_id_idx
  on public.analytics_events (visitor_id);
create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);

alter table public.analytics_events enable row level security;

drop policy if exists "public_insert_analytics" on public.analytics_events;
create policy "public_insert_analytics"
on public.analytics_events
for insert
to anon, authenticated
with check (
  char_length(visitor_id) between 1 and 80
  and char_length(event_name) between 1 and 60
  and event_name in ('page_view', 'nandolino_open', 'whatsapp_click', 'project_click')
);

drop policy if exists "authenticated_read_analytics" on public.analytics_events;
create policy "authenticated_read_analytics"
on public.analytics_events
for select
to authenticated
using (true);

-- Não crie policy de UPDATE ou DELETE para visitantes.
